language: python
fast_finish: true

install:
  - git clone https://github.com/servo/servo
  - cd servo
  - GIT_PAGER= git log -n 1

  # Merge the rustup branch if it exists
  # Disabled because it makes Travis hang?
  # https://travis-ci.org/servo/servo-with-rust-nightly/builds/204775678#L761
  #- if git rev-parse --verify origin/rustup; then git merge origin/rustup; fi

  - curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain nightly -y
  - source ~/.profile
  - rustc +nightly --version -v
  - cargo +nightly --version -v

matrix:
  include:
    - script:
      - python ../better_travis_wait.py cargo +nightly build
      - cargo +nightly test
      - cargo +nightly test -p stylo_tests

    - script:
      # Compiling everything takes more than the already-extended 75 min time limit,
      # so only compile style and dependencies.
      - python ../better_travis_wait.py cargo +nightly build --release -p style --manifest-path ports/servo/Cargo.toml

dist: trusty
sudo: 9000
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo add-apt-repository 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main' -y
  - sudo apt-get update -q
  - sudo apt-get install clang-3.9 llvm-3.9 llvm-3.9-runtime -y
  - export LLVM_CONFIG=/usr/lib/llvm-3.9/bin/llvm-config
  - export CC=gcc-5 CXX=g++-5
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: 'ppa:jonathonf/ffmpeg-3'
    packages:
      - cmake
      - dbus-x11
      - gcc-5
      - g++-5
      - gperf
      - libavcodec-dev
      - libavformat-dev
      - libpulse-dev
      - libswscale-dev
      - libswresample-dev
      - pulseaudio
      - python-virtualenv
      - xorg-dev
      - ccache
      - libdbus-glib-1-dev
cache:
  directories:
    - $HOME/.cargo
    - $HOME/.ccache
env: CCACHE=/usr/bin/ccache CARGO_INCREMENTAL=0
notifications:
  email: false
  irc:
    channels: "irc.mozilla.org#servo"
    on_success: never
    on_failure: always
    template: "Servo failed to build with Rust nightly: %{build_url} CC nox, SimonSapin, jntrnr"
